export enum ErrorCodes {
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INVALID_OBJECT_ID = 'INVALID_OBJECT_ID',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
